export const armor = [
  {
    name: "Jerkin",
    primary: 4,
    modifier: -1,
    cost: "9g",
  },
  {
    name: "Padded Tunic",
    primary: 5,
    modifier: -1,
    cost: "10g",
  },
  {
    name: "Quilted Coat",
    primary: 3,
    modifier: -1,
    cost: "11g",
  },
  {
    name: "Hide Doublet",
    primary: 2,
    modifier: -1,
    cost: "12g",
  },
  {
    name: "Bishop's Mantle",
    primary: 5,
    secondary: 4,
    modifier: -1,
    cost: "18g",
  },
  {
    name: "Long Leather Jacket",
    primary: 3,
    secondary: 2,
    modifier: -1,
    cost: "20g",
  },
  {
    name: "Leather Breast Plate",
    primary: 6,
    secondary: 1,
    modifier: -1,
    cost: "25g",
  },
  {
    name: "Leather Bracers",
    primary: 6,
    secondary: 3,
    modifier: -1,
    cost: "26g",
  },
  {
    name: "Brigandine Overcoat",
    primary: 4,
    secondary: 3,
    modifier: -1,
    cost: "30g",
  },
  {
    name: "Studded Buckler",
    primary: 3,
    secondary: 1,
    modifier: -1,
    cost: "34g",
  },
  {
    name: "Steel Buckler",
    primary: 4,
    secondary: 1,
    modifier: -2,
    cost: "40g",
  },
  {
    name: "Wooden Shield",
    primary: 5,
    secondary: 3,
    modifier: -2,
    cost: "42g",
  },
  {
    name: "Banded Shield",
    primary: 6,
    secondary: 5,
    modifier: -2,
    cost: "45g",
  },
  {
    name: "Shoulder Platelets",
    primary: 1,
    secondary: 1,
    modifier: -2,
    cost: "48g",
  },
  {
    name: "Mail Coif",
    primary: 6,
    secondary: 4,
    modifier: -2,
    cost: "50g",
  },
  {
    name: "Metal Bracers",
    primary: 3,
    secondary: 3,
    modifier: -2,
    cost: "55g",
  },
  {
    name: "Helmet",
    primary: 3,
    secondary: 2,
    modifier: -2,
    cost: "60g",
  },
  {
    name: "Winged Helmet",
    primary: 6,
    secondary: 2,
    modifier: -2,
    cost: "75g",
  },
  {
    name: "Great Helm",
    primary: [4, 1],
    secondary: 3,
    modifier: -3,
    cost: "95g",
  },
  {
    name: "Gauntlets",
    primary: [6, 2],
    secondary: 2,
    modifier: -3,
    cost: "120g",
  },
  {
    name: "Long Gauntlets",
    primary: [5, 3],
    secondary: 3,
    modifier: -3,
    cost: "155g",
  },
  {
    name: "Scale Jacket",
    primary: [5, 2],
    secondary: 4,
    modifier: -3,
    cost: "200g",
  },
  {
    name: "Exquisite Scale Jacket",
    primary: [6, 1],
    secondary: 4,
    modifier: -3,
    cost: "280g",
  },
  {
    name: "Chain Mail Shirt",
    primary: [4, 2],
    secondary: 3,
    modifier: -3,
    cost: "320g",
  },
  {
    name: "Metal Breast Plate",
    primary: [6, 1],
    secondary: 3,
    modifier: -3,
    cost: "440g",
  },
  {
    name: "Reinforced Banded Mail",
    primary: [6, 3],
    secondary: [4, 3],
    modifier: -4,
    cost: "620g",
  },
  {
    name: "Reinforced Banded Mail",
    primary: [5, 3],
    secondary: [4, 2],
    modifier: -4,
    cost: "650g",
  },
];
