export const maneuvers = [
  {
    weapon: "longsword",
    level: 1,
    name: "Disguised Swoop",
    primary: 1,
    secondary: 2,
    damage: "d6 + 2",
  },
  {
    weapon: "longsword",
    level: 1,
    name: "Incisive Cut",
    primary: 5,
    secondary: 2,
    damage: "d6 + 1",
  },
  {
    weapon: "longsword",
    level: 1,
    name: "Thrust",
    primary: 3,
    secondary: 2,
    damage: "d6",
  },
  {
    weapon: "longsword",
    level: 1,
    name: "Swing",
    primary: 4,
    secondary: 3,
    damage: "d6 - 1",
  },
  {
    weapon: "longsword",
    level: 1,
    name: "Slice",
    primary: 3,
    secondary: 3,
    damage: "d6 - 1",
  },
  {
    weapon: "longsword",
    level: 1,
    name: "Hack",
    primary: 4,
    secondary: 2,
    damage: "d6 - 1",
  },
  {
    weapon: "longsword",
    level: 1,
    name: "Stab",
    primary: 2,
    secondary: 4,
    damage: "d6 - 1",
  },
  {
    weapon: "longsword",
    level: 1,
    name: "Carving Blow",
    primary: 4,
    secondary: 1,
    damage: "d6",
  },
  {
    weapon: "longsword",
    level: 1,
    name: "Biting Stroke",
    primary: 2,
    secondary: 3,
    damage: "d6 + 1",
  },
  {
    weapon: "longsword",
    level: 1,
    name: "Heavy Slash",
    primary: 6,
    secondary: 4,
    damage: "d6 + 2",
  },
  {
    weapon: "greataxe",
    level: 1,
    name: "Weighted Charge",
    primary: 1,
    secondary: 2,
    damage: "d6 + 3",
  },
  {
    weapon: "greataxe",
    level: 1,
    name: "Low Swish",
    primary: 5,
    secondary: 2,
    damage: "d6 + 1",
  },
  {
    weapon: "greataxe",
    level: 1,
    name: "Hack",
    primary: 3,
    secondary: 2,
    damage: "d6",
  },
  {
    weapon: "greataxe",
    level: 1,
    name: "Carve",
    primary: 4,
    secondary: 3,
    damage: "d6 - 1",
  },
  {
    weapon: "greataxe",
    level: 1,
    name: "Chop",
    primary: 3,
    secondary: 3,
    damage: "d6 - 1",
  },
  {
    weapon: "greataxe",
    level: 1,
    name: "Crack",
    primary: 4,
    secondary: 2,
    damage: "d6 - 1",
  },
  {
    weapon: "greataxe",
    level: 1,
    name: "Cleave",
    primary: 2,
    secondary: 4,
    damage: "d6 - 1",
  },
  {
    weapon: "greataxe",
    level: 1,
    name: "Sharp Slash",
    primary: 4,
    secondary: 1,
    damage: "d6",
  },
  {
    weapon: "greataxe",
    level: 1,
    name: "Direct Jab",
    primary: 2,
    secondary: 3,
    damage: "d6 + 1",
  },
  {
    weapon: "greataxe",
    level: 1,
    name: "Incisive Heft",
    primary: 6,
    secondary: 4,
    damage: "d6 + 3",
  },
  {
    weapon: "mace",
    level: 1,
    name: "Solid Belting",
    primary: 1,
    secondary: 2,
    damage: "d6 + 2",
  },
  {
    weapon: "mace",
    level: 1,
    name: "Pommel Thump",
    primary: 5,
    secondary: 2,
    damage: "d6 + 1",
  },
  {
    weapon: "mace",
    level: 1,
    name: "Carving Hit",
    primary: 3,
    secondary: 2,
    damage: "d6 + 1",
  },
  {
    weapon: "mace",
    level: 1,
    name: "Pummel",
    primary: 4,
    secondary: 3,
    damage: "d6 - 1",
  },
  {
    weapon: "mace",
    level: 1,
    name: "Bludgeon",
    primary: 3,
    secondary: 3,
    damage: "d6",
  },
  {
    weapon: "mace",
    level: 1,
    name: "Bash",
    primary: 4,
    secondary: 2,
    damage: "d6",
  },
  {
    weapon: "mace",
    level: 1,
    name: "Bat",
    primary: 2,
    secondary: 4,
    damage: "d6 - 1",
  },
  {
    weapon: "mace",
    level: 1,
    name: "Swinging Club",
    primary: 4,
    secondary: 1,
    damage: "d6 + 1",
  },
  {
    weapon: "mace",
    level: 1,
    name: "Sudden Whomp",
    primary: 2,
    secondary: 3,
    damage: "d6 + 1",
  },
  {
    weapon: "mace",
    level: 1,
    name: "Drubbing",
    primary: 6,
    secondary: 4,
    damage: "d6 + 2",
  },
];
