export const potions = [
  {
    name: "Potion of Constancy",
    effect: "+1 Precision and +1 Discipline for 1 dungeon level",
    duration: "Instant",
    cost: 45,
  },
  {
    name: "Potion of Dexterous Actions",
    effect: "-2 Shift from your opponent's Shift Points for 1 whole combat",
    duration: "One Combat",
    cost: 100,
  },
  {
    name: "Potion of Divine Shield",
    effect: "-10 damage from each hit you take for 1 whole combat",
    duration: "One Combat",
    cost: 200,
  },
  {
    name: "Potion of Domination",
    effect: "+2 Discipline for 1 dungeon level",
    duration: "Instant",
    cost: 50,
  },
  {
    name: "Potion of Examination",
    effect: "+2 to the treasure rolls in 1 room",
    duration: "Instant",
    cost: 10,
  },
  {
    name: "Potion of Extra Healing",
    effect: "Heal up to 30 Health Points",
    duration: "Instant",
    cost: 28,
  },
  {
    name: "Potion of Fidelity",
    effect: "+1 Precision for 1 dungeon level",
    duration: "Instant",
    cost: 8,
  },
  {
    name: "Potion of Finesse",
    effect: "+2 Shift for 1 whole combat",
    duration: "One Combat",
    cost: 50,
  },
  {
    name: "Potion of Further Health",
    effect: "Gain 25 Health Points (can exceed baseline level)",
    duration: "Instant",
    cost: 40,
  },
  {
    name: "Potion of Gain Health",
    effect: "Gain 15 Health Points (can exceed baseline level)",
    duration: "Instant",
    cost: 25,
  },
  {
    name: "Potion of Healing",
    effect: "Heal up to 10 Health Points",
    duration: "Instant",
    cost: 18,
  },
  {
    name: "Potion of Mighty Strength",
    effect: "+2 damage per hit for 1 whole combat",
    duration: "One Combat",
    cost: 20,
  },
  {
    name: "Potion of Phasing",
    effect: "Phase through one locked door ignoring the locked status",
    duration: "Instant",
    cost: 4,
  },
  {
    name: "Potion of Prowess",
    effect: "+1 Shift for 1 whole combat",
    duration: "One Combat",
    cost: 26,
  },
  {
    name: "Potion of Rancid Breath",
    effect: "Do an extra 5 points of damage per round for 1 whole combat",
    duration: "One Combat",
    cost: 75,
  },
  {
    name: "Potion of Regeneration",
    effect: "Heal up to 60 Health Points",
    duration: "Instant",
    cost: 80,
  },
  {
    name: "Potion of Resist Magic",
    effect:
      "Ignore 1 successful enemy manoeuvre against you that is magic based",
    duration: "Instant",
    cost: 10,
  },
  {
    name: "Potion of Shield Aura",
    effect: "-1 Damage taken per round in 1 whole combat",
    duration: "One Combat",
    cost: 18,
  },
  {
    name: "Potion of Speed Blast",
    effect: "+2 free attacks at the start of 1 combat",
    duration: "One Combat",
    cost: 13,
  },
  {
    name: "Potion of Steadiness",
    effect: "+2 Precision for 1 dungeon level",
    duration: "Instant",
    cost: 40,
  },
  {
    name: "Potion of Strength",
    effect: "+1 damage per hit for 1 whole combat",
    duration: "One Combat",
    cost: 15,
  },
  {
    name: "Potion of Willpower",
    effect: "+1 Discipline for 1 dungeon level",
    duration: "Instant",
    cost: 30,
  },
];
