export const scrolls = [
  {
    name: "Scroll of Balance",
    description:
      "You sense an inner stability and become aware of magic flowing through the air.",
    duration: "Until Used",
    orbit: "Faculty",
    dispel: [],
    cost: 15,
    fail: 1,
    effect: "+1 Discipline for 1 Dungeon Level",
  },
  {
    name: "Scroll of Brute Force",
    description:
      "Your muscles tighten and bulge and you feel strength coursing through your body.",
    duration: "Next Combat",
    orbit: "Metamorph",
    dispel: [],
    cost: 17,
    fail: 2,
    effect: "+2 Damage for 1 Combat",
  },
  {
    name: "Scroll of Deep Focus",
    description:
      "You feel connected to the streams of magic energy and control them with ease.",
    duration: "Until Used",
    orbit: "Faculty",
    dispel: [],
    cost: 25,
    fail: -1,
    effect: "+2 Discipline for 1 Dungeon Level",
  },
  {
    name: "Scroll of Distract",
    description:
      "You enter the enemy's mind and turn their thoughts against their companion.",
    duration: "Instant",
    orbit: "Psyche",
    dispel: [],
    cost: 30,
    fail: 1,
    effect: "If you face 2 foes 1 leaves",
  },
  {
    name: "Scroll of Fireball",
    description:
      "You blast a ball of fire from your open palm at your enemy, who bursts into flames.",
    duration: "Instant",
    orbit: "Primordial",
    dispel: [4],
    cost: 20,
    fail: -1,
    effect: "Causes 20 Damage",
  },
  {
    name: "Scroll of Flaming Weapon",
    description:
      "Flames erupt from the blade of your weapon and burn those you strike.",
    duration: "Next Combat",
    orbit: "Primordial",
    dispel: [1],
    cost: 32,
    fail: 0,
    effect: "+3 Damage for 1 Combat",
  },
  {
    name: "Scroll of Fleeting Action",
    description:
      "You feel your pulse quicken and you movements become swift and precise.",
    duration: "Next Combat",
    orbit: "Faculty",
    dispel: [3],
    cost: 10,
    fail: -1,
    effect: "+2 Shift for 1 Combat",
  },
  {
    name: "Scroll of Insightful Combat",
    description:
      "The world slows and details seem clearer as you study your opponent's movements.",
    duration: "Next Combat",
    orbit: "Psyche",
    dispel: [],
    cost: 70,
    fail: -2,
    effect: "+20% XP from 1 Combat",
  },
  {
    name: "Scroll of Invisibility",
    description:
      "You glance down to see that your body has disappeared and that you have vanished.",
    duration: "Next Combat",
    orbit: "Metamorph",
    dispel: [5],
    cost: 21,
    fail: -1,
    effect: "Avoid 1 Combat and room contents",
  },
  {
    name: "Scroll of Lightning Strike",
    description:
      "A fork of blue lightning explodes from your chest to strike your foe with unholy force.",
    duration: "Instant",
    orbit: "Primordial",
    dispel: [3, 6],
    cost: 50,
    fail: -3,
    effect: "1 strike of 50 Damage",
  },
  {
    name: "Scroll of Melt Metal",
    description:
      "You concentrate on the metal and watch it melt into a soft dripping gloop.",
    duration: "Instant",
    orbit: "Metamorph",
    dispel: [],
    cost: 18,
    fail: 0,
    effect: "Destroy 1 lock or interrupt armor",
  },
  {
    name: "Scroll of Mental Whip",
    description:
      "You reach out a thought into their mind and it transforms to become a barbed lash.",
    duration: "Instant",
    orbit: "Psyche",
    dispel: [],
    cost: 20,
    fail: -1,
    effect: "1 strike of 10 Damage",
  },
  {
    name: "Scroll of Paralysis",
    description:
      "You clench your fist and focus on one foe and they freeze to the spot motionless.",
    duration: "Instant",
    orbit: "Psyche",
    dispel: [],
    cost: 22,
    fail: 1,
    effect: "3 free swings in 1 Combat",
  },
  {
    name: "Scroll of Reflexes",
    description:
      "Warmth floods your body, making you feel at ease and unexpectedly flexible.",
    duration: "Next Combat",
    orbit: "Faculty",
    dispel: [],
    cost: 10,
    fail: 2,
    effect: "+1 Shift for 1 Combat",
  },
  {
    name: "Scroll of Steady Hand",
    description:
      "You sense your movements as if magnified, allowing you to steady yourself.",
    duration: "Until Used",
    orbit: "Facutly",
    dispel: [],
    cost: 13,
    fail: -1,
    effect: "+1 Precision for 1 Dungeon Level",
  },
  {
    name: "Scroll of Sunder",
    description:
      "There is a loud crack and the ceiling above your foe collapses inwards on them.",
    duration: "Instant",
    orbit: "Metamorph",
    dispel: [2],
    cost: 30,
    fail: -1,
    effect: "1 Strike of 20 Damage to all foes",
  },
  {
    name: "Scroll of Surging Health",
    description:
      "You watch as your woulds close and heal and renewed vigour surges through you.",
    duration: "Instant",
    orbit: "Metamorph",
    dispel: [4],
    cost: 55,
    fail: -1,
    effect: "+20 Health Points",
  },
  {
    name: "Scroll of Swamp Lung",
    description:
      "You watch as a torrent of swamp water pours from your foe's mouth.",
    duration: "Instant",
    orbit: "Primordial",
    dispel: [5],
    cost: 25,
    fail: -1,
    effect: "1 free swing + 20 Damage",
  },
];
